baseURL = "https://blog.openmls.tech"
languageCode = "en-us"
title = "OpenMLS"
theme = "hugo-papermod"

[pagination]
pagerSize = 10

[params]
smartToc = true
katex = true
mainSections = ["posts"]
ShowFullTextinRSS = true

[params.homeInfoParams]
title = "OpenMLS"
content = "The Open MLS Implementation"
[[params.socialIcons]]
name = "github"
url = "https://github.com/openmls/openmls"
[[params.socialIcons]]
name = "email"
url = "mailto:hello@openmls.tech"
[[params.socialIcons]]
name = "website"
url = "https://openmls.tech/"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/openmls/openmls"
weight = 2
